sudo: false

language: cpp

compiler:
  - g++
  - clang++

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  
addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-5
      - clang++-3.8

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - test/test_all

notifications:
  email: false
